name: Maven report

on: [push,pull_request]

jobs:
  build:

    if: "!startsWith(github.ref, 'refs/heads/feature/')"  # Esegue se non si trova nella branch feature/*
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with JaCoCo
        run: mvn test jacoco:report

      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn coveralls:report